# Generated by Django 5.1.7 on 2025-06-09 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('spotify_id', models.CharField(blank=True, max_length=100, null=True)),
                ('spotify_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ritmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('popularidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musica.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('track_id', models.CharField(blank=True, max_length=100, null=True)),
                ('popularidad', models.IntegerField(default=0)),
                ('duracion_ms', models.IntegerField(default=0)),
                ('explicito', models.BooleanField(default=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='musica.album')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='musica.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='ritmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artistas', to='musica.ritmo'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='musica.artista')),
            ],
        ),
    ]
